
services:
  oracle-db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: oracle21c-lab-acidentes
    hostname: oracle-db
    restart: unless-stopped
    
    # Variáveis de ambiente
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=standard
      - ORACLE_PDB=XEPDB1
      - ORACLE_SID=XE
    
    # Portas
    ports:
      - "1521:1521"    # Porta principal do Oracle
      - "5500:5500"    # Oracle Enterprise Manager
    
    # Volumes para persistência
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle_backup:/opt/oracle/backup
      - ./scripts-sql:/opt/oracle/scripts/custom:ro
      - ./logs:/opt/oracle/diag:rw
    
    # Configurações de memória e recursos (mínimo 2GB para Oracle XE)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '3.0'
    
    # Configurações de rede
    networks:
      - oracle-network
    
    # Healthcheck
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s sys/OraclePassword123@localhost:1521/XE as sysdba | grep -q '1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # Opcional: Container para administração
  oracle-admin:
    image: adminer:latest
    container_name: oracle-admin
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=oracle-db:1521
    networks:
      - oracle-network
    depends_on:
      oracle-db:
        condition: service_healthy

# Volumes nomeados para persistência
volumes:
  oracle_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/oracle
  oracle_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backup

# Rede dedicada
networks:
  oracle-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
